Repository Spoon-Lab/our-journey-fe, pull requests merged in 2024-09, with the labels that each got.

#2 [Docs] 이슈 및 PR 템플릿 업데이트
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/chore-template.md
  .github/ISSUE_TEMPLATE/design-template.md
  .github/ISSUE_TEMPLATE/feat-template.md
  .github/ISSUE_TEMPLATE/hotfix-template.md
  .github/ISSUE_TEMPLATE/index.md
  .github/ISSUE_TEMPLATE/initial-template.md
  .github/ISSUE_TEMPLATE/refector-template.md
  .github/pull_request_template.md
Labels: documentation

#9 [Feat] 공용 Layout 및 Header 컴포넌트 제작
  next.config.mjs
  package.json
  src/assets/icons/Bell.svg
  src/components/header/index.tsx
  src/components/header/style.module.scss
  src/components/layouts/index.ts
  src/components/layouts/index.tsx
  src/components/layouts/style.module.scss
  src/components/providers/ReactQuery.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/globals.scss
Labels: feat

#10 [Chore] workflow 설정
  .github/workflows/auto-assign.yml
  .github/workflows/branch-check.yml
  .github/workflows/build-test.yml
  .gitignore
  .husky/pre-commit
Labels: chore

#16 [Feat] 공용 Input 컴포넌트 제작
  src/components/component/input/index.tsx
  src/components/component/input/style.module.scss
Labels: feat

#15 [Feat] 공용 Layout 및 Header 컴포넌트 제작
  next.config.mjs
  package.json
  src/assets/icons/Bell.svg
  src/assets/icons/icons.ts
  src/components/header/index.tsx
  src/components/header/style.module.scss
  src/components/layouts/index.ts
  src/components/layouts/index.tsx
  src/components/layouts/style.module.scss
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: feat

#11 [Chore] husky, commitlint (#8)
  .commitlintrc.json
  .github/workflows/build-test.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .huskyrc
  package.json
Labels: chore

#18 [Design] 색상 및 폰트 SCSS 변수화
  src/constants/api.ts
  src/constants/router.ts
  src/pages/_document.tsx
  src/styles/color.scss
  src/styles/font.scss
  src/styles/globals.scss
  src/styles/variable.scss
Labels: design

#31 [Feat] 카테고리 및 검색 페이지 구현 작업
  public/image-domestic.webp
  public/image-foreign.webp
  src/assets/icons/icon-arrow-back.svg
  src/assets/icons/index.ts
  src/components/feed-grid/index.tsx
  src/components/feed-grid/style.module.scss
  src/components/grid-card/index.tsx
  src/components/grid-card/style.module.scss
  src/components/header/index.tsx
  src/components/header/style.module.scss
  src/components/nav-bar/index.tsx
  src/constants/router.ts
  src/hooks/use-current-keyword.ts
  src/hooks/use-get-feed.ts
  src/mocks/contents.ts
  src/pages/category/component/category-area/index.tsx
  src/pages/category/component/category-area/style.module.scss
  src/pages/category/component/current-search-area/index.tsx
  src/pages/category/component/current-search-area/style.module.scss
  src/pages/category/index.tsx
  src/pages/category/style.module.scss
  src/pages/search/index.tsx
  src/pages/search/style.module.scss
  src/types/contents.ts
Labels: feat

#29 [Feat] 로그인/회원가입/비밀번호 재설정 페이지 구현
  .gitignore
  package.json
  public/images/background.jpeg
  public/images/yellowImg.png
  src/assets/icons/Google.svg
  src/assets/icons/Photo.svg
  src/assets/icons/arrow.svg
  src/assets/icons/index.ts
  src/components/auth-Intro-text/index.tsx
  src/components/auth-Intro-text/style.module.scss
  src/components/auth-header/index.tsx
  src/components/auth-header/style.module.scss
  src/components/button/index.tsx
  src/components/button/style.module.scss
  src/components/input/index.tsx
  src/components/input/style.module.scss
  src/components/layouts/auth-layout/index.tsx
  src/components/layouts/auth-layout/style.module.scss
  src/constants/api.ts
  src/constants/router.ts
  src/hooks/auth/use-email-request.ts
  src/hooks/auth/use-login.ts
  src/hooks/auth/use-reset-password.ts
  src/hooks/auth/use-signup.ts
  src/hooks/use-image.ts
  src/hooks/use-upload-img.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/index.tsx
  src/pages/login/components/login-form/index.tsx
  src/pages/login/components/login-form/style.module.scss
  src/pages/login/components/navbar/index.tsx
  src/pages/login/components/navbar/style.module.scss
  src/pages/login/index.tsx
  src/pages/login/style.module.scss
  src/pages/reset-password/[...id].tsx
  src/pages/reset-password/components/email-form/index.tsx
  src/pages/reset-password/components/email-form/style.module.scss
  src/pages/reset-password/components/reset-form/index.tsx
  src/pages/reset-password/components/reset-form/style.module.scss
  src/pages/reset-password/email/index.tsx
  src/pages/reset-password/email/style.module.scss
  src/pages/reset-password/index.tsx
  src/pages/reset-password/style.module.scss
  src/pages/signup/components/signup-form/index.tsx
  src/pages/signup/components/signup-form/style.module.scss
  src/pages/signup/index.tsx
  src/pages/signup/style.module.scss
  src/pages/style.module.scss
  src/styles/globals.scss
  src/types/auth.ts
  src/utils/validate.ts
Labels: feat

#34 [Feat] 메인 및 카테고리 페이지 상세화
  public/image-main-background.webp
  src/assets/icons/icon-flight.svg
  src/assets/icons/icon-luggage.svg
  src/assets/icons/icon-write.svg
  src/assets/icons/index.ts
  src/components/auth-header/index.tsx
  src/components/chip/index.tsx
  src/components/chip/style.module.scss
  src/components/grid-card/index.tsx
  src/components/header/style.module.scss
  src/components/layouts/style.module.scss
  src/components/nav-bar/style.module.scss
  src/components/search-bar/index.tsx
  src/components/search-bar/style.module.scss
  src/constants/router.ts
  src/hooks/use-active-scroll.ts
  src/hooks/use-category-list.ts
  src/hooks/use-change-carousel.ts
  src/mocks/banners.ts
  src/mocks/categories.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/main/component/banner-carousel/index.tsx
  src/pages/main/component/banner-carousel/style.module.scss
  src/pages/main/component/create-box/index.tsx
  src/pages/main/component/create-box/style.module.scss
  src/pages/main/component/feed-grid/index.tsx
  src/pages/main/component/feed-grid/style.module.scss
  src/pages/main/component/grid-card/index.tsx
  src/pages/main/component/grid-card/style.module.scss
  src/pages/main/component/sort-container/style.module.scss
  src/pages/main/component/top-banner/index.tsx
  src/pages/main/component/top-banner/style.module.scss
  src/pages/main/index.tsx
  src/pages/main/style.module.scss
  src/pages/search/index.tsx
Labels: feat

#32 [Feat] 프로필 페이지 구현
  next.config.mjs
  src/assets/icons/Home.svg
  src/assets/icons/Menu.svg
  src/assets/icons/Search.svg
  src/assets/icons/article.svg
  src/assets/icons/campaign.svg
  src/assets/icons/chevron_forward.svg
  src/assets/icons/default-profile.svg
  src/assets/icons/edit.svg
  src/assets/icons/group-profile.svg
  src/assets/icons/index.ts
  src/assets/icons/keyboard_arrow_down.svg
  src/assets/icons/keyboard_arrow_up.svg
  src/assets/icons/person.svg
  src/components/layouts/profile-layout/index.tsx
  src/components/layouts/profile-layout/style.module.scss
  src/components/menu-bar/index.tsx
  src/components/menu-bar/style.module.scss
  src/components/modal/index.tsx
  src/components/modal/style.module.scss
  src/components/portal/index.tsx
  src/constants/router.ts
  src/hooks/auth/use-logout.ts
  src/hooks/profile/use-get-my-contents.ts
  src/hooks/profile/use-get-profile.ts
  src/hooks/use-upload-img.ts
  src/mocks/profile.ts
  src/pages/_document.tsx
  src/pages/profile/[id].tsx
  src/pages/profile/components/content/index.tsx
  src/pages/profile/components/content/style.module.scss
  src/pages/profile/components/nav-item/index.tsx
  src/pages/profile/components/nav-item/style.module.scss
  src/pages/profile/components/profile-header/index.tsx
  src/pages/profile/components/profile-header/style.module.scss
  src/pages/profile/components/user-settings/index.tsx
  src/pages/profile/components/user-settings/style.module.scss
  src/pages/profile/edit/[id].tsx
  src/pages/profile/edit/style.module.scss
  src/pages/profile/style.module.scss
  src/types/contents.ts
  src/types/profile.ts
Labels: feat

#39 [Feat] 메인 및 카테고리 페이지 상세화
  error-boundary.ts
  public/favicon.ico
  public/image-grid-card-default1.webp
  public/image-grid-card-default2.webp
  public/image-main-background.webp
  public/image-not-found-background.webp
  public/image-opengraph.webp
  public/next.svg
  public/vercel.svg
  src/components/feed-grid/style.module.scss
  src/components/grid-card/index.tsx
  src/components/search-bar/index.tsx
  src/constants/api.ts
  src/hooks/contents/use-active-scroll.ts
  src/hooks/contents/use-category-list.ts
  src/hooks/contents/use-change-carousel.ts
  src/hooks/contents/use-current-keyword.ts
  src/hooks/contents/use-get-contents.ts
  src/hooks/contents/use-intersection-observer.ts
  src/hooks/use-category-list.ts
  src/hooks/use-get-feed.ts
  src/libs/pre-axios.ts
  src/pages/404.tsx
  src/pages/_document.tsx
  src/pages/category/component/category-area/index.tsx
  src/pages/category/component/category-area/style.module.scss
  src/pages/category/component/current-search-area/index.tsx
  src/pages/category/index.tsx
  src/pages/main/component/banner-carousel/index.tsx
  src/pages/main/component/banner-carousel/style.module.scss
  src/pages/main/index.tsx
  src/pages/main/style.module.scss
  src/pages/search/index.tsx
  src/pages/search/style.module.scss
  src/pages/style.module.scss
  src/types/contents.ts
Labels: feat

#43 [Feat] auth 관련 api 연결
  src/components/layouts/auth-layout/style.module.scss
  src/components/toast/index.tsx
  src/components/toast/style.module.scss
  src/constants/router.ts
  src/hooks/auth/use-login.ts
  src/hooks/auth/use-signup.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/login/(components)/login-form/index.tsx
  src/pages/login/(components)/login-form/style.module.scss
  src/pages/login/(components)/navbar/index.tsx
  src/pages/login/(components)/navbar/style.module.scss
  src/pages/login/components/login-form/index.tsx
  src/pages/login/google/index.tsx
  src/pages/login/google/style.module.scss
  src/pages/login/index.tsx
  src/pages/signup/(components)/signup-form/index.tsx
  src/pages/signup/(components)/signup-form/style.module.scss
  src/pages/signup/components/signup-form/index.tsx
  src/pages/signup/index.tsx
  src/types/next-auth.d.ts
  src/utils/validate.ts
  tsconfig.json
Labels: feat

#46 [Feat] 메인 및 상세 관련 자체 QA 수정사항 적용
  src/components/grid-card/index.tsx
  src/components/layouts/style.module.scss
  src/components/nav-bar/index.tsx
  src/components/nav-bar/style.module.scss
  src/components/search-bar/style.module.scss
  src/constants/api.ts
  src/hooks/contents/use-get-contents.ts
  src/pages/_document.tsx
  src/pages/main/component/create-box/index.tsx
  src/pages/main/style.module.scss
  src/pages/search/style.module.scss
Labels: feat

#48 [Feat] auth 관련 에러 처리 수정 및 리프레시 토큰 로직 추가
  package.json
  public/lottie-loading.json
  src/components/lottie-loading/index.tsx
  src/components/lottie-loading/style.module.scss
  src/constants/router.ts
  src/hooks/auth/use-email-request.ts
  src/hooks/auth/use-login.ts
  src/hooks/auth/use-reset-password.ts
  src/hooks/auth/use-signup.ts
  src/libs/axios.ts
  src/pages/login/google/index.tsx
  src/pages/login/google/style.module.scss
  src/pages/reset-password/components/email-form/index.tsx
  src/pages/reset-password/components/email-form/style.module.scss
  src/pages/reset-password/components/reset-form/index.tsx
  src/pages/reset-password/components/reset-form/style.module.scss
Labels: feat

#51 [Feat] axios 경로 분리
  src/assets/icons/icon-menu.svg
  src/components/nav-bar/index.tsx
  src/hooks/auth/use-email-request.ts
  src/hooks/auth/use-login.ts
  src/hooks/auth/use-logout.ts
  src/hooks/auth/use-reset-password.ts
  src/hooks/auth/use-signup.ts
  src/hooks/profile/use-get-profile.ts
  src/hooks/use-image.ts
  src/hooks/use-upload-img.ts
  src/libs/auth-axios.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/login/google/index.tsx
  src/pages/profile/(components)/content/index.tsx
  src/pages/profile/(components)/content/style.module.scss
  src/pages/profile/(components)/nav-item/index.tsx
  src/pages/profile/(components)/nav-item/style.module.scss
  src/pages/profile/(components)/profile-header/index.tsx
  src/pages/profile/(components)/profile-header/style.module.scss
  src/pages/profile/(components)/user-settings/index.tsx
  src/pages/profile/(components)/user-settings/style.module.scss
  src/pages/profile/edit/index.tsx
  src/pages/profile/edit/style.module.scss
  src/pages/profile/index.tsx
  src/pages/signup/(components)/signup-form/index.tsx
Labels: feat

#57 [Feat] 로그아웃 api 연결 & 리프레시 수정
  src/hooks/auth/use-logout.ts
  src/libs/auth-axios.ts
  src/libs/axios.ts
  src/pages/profile/(components)/user-settings/index.tsx
  src/pages/profile/index.tsx
Labels: feat

#60 [Feat] 프로필 팔로잉 ui 임시 삭제
  src/pages/profile/index.tsx
Labels: feat

#55 [Feat] 메인 및 카테고리, 검색 자체 QA 관련 미흡 및 문제 사항들 수정
  README.md
  error-boundary.ts
  src/components/header/style.module.scss
  src/components/lottie-loading/style.module.scss
  src/components/nav-bar/index.tsx
  src/constants/router.ts
  src/pages/404.tsx
  src/pages/main/component/create-box/index.tsx
  src/pages/main/style.module.scss
  src/pages/need-login/index.tsx
  src/pages/need-login/style.module.scss
  src/pages/search/index.tsx
  src/pages/signup/style.module.scss
Labels: feat

#63 [Feat] 로그아웃 로직 임시 변경
  src/pages/profile/(components)/user-settings/index.tsx
Labels: feat

#67 [Feat] 로그아웃 로직 추가
  src/pages/profile/(components)/user-settings/index.tsx
Labels: feat

#69 [Bug] 배포 이슈 수정
  README.md
Labels: bug

#72 [Feat] landing ui 수정 & toast provider 로 변경
  src/components/layouts/auth-layout/style.module.scss
  src/components/layouts/profile-layout/style.module.scss
  src/hooks/auth/use-email-request.ts
  src/hooks/auth/use-login.ts
  src/hooks/auth/use-logout.ts
  src/hooks/auth/use-reset-password.ts
  src/hooks/auth/use-signup.ts
  src/hooks/profile/use-update-my-profile.ts
  src/hooks/use-upload-img.ts
  src/libs/axios.ts
  src/pages/login/(components)/login-form/index.tsx
  src/pages/login/(components)/login-form/style.module.scss
  src/pages/profile/(components)/user-settings/index.tsx
  src/pages/profile/edit/index.tsx
  src/pages/profile/edit/style.module.scss
  src/pages/profile/index.tsx
  src/pages/reset-password/components/email-form/index.tsx
  src/pages/reset-password/components/email-form/style.module.scss
  src/pages/reset-password/components/reset-form/index.tsx
  src/pages/reset-password/components/reset-form/style.module.scss
  src/pages/signup/(components)/signup-form/index.tsx
  src/pages/signup/(components)/signup-form/style.module.scss
  src/pages/style.module.scss
Labels: feat

#74 [Bug] 로그아웃 시 캐시 문제 & ui 수정
  src/components/auth-Intro-text/index.tsx
  src/hooks/auth/use-login.ts
  src/hooks/auth/use-logout.ts
  src/libs/auth-axios.ts
  src/libs/axios.ts
  src/pages/login/(components)/login-form/index.tsx
  src/pages/login/(components)/login-form/style.module.scss
  src/pages/login/(components)/navbar/style.module.scss
  src/pages/login/index.tsx
  src/pages/login/style.module.scss
  src/pages/reset-password/components/email-form/style.module.scss
  src/pages/reset-password/components/reset-form/index.tsx
  src/pages/reset-password/components/reset-form/style.module.scss
  src/pages/reset-password/email/style.module.scss
  src/pages/reset-password/style.module.scss
  src/pages/signup/(components)/signup-form/index.tsx
  src/pages/signup/(components)/signup-form/style.module.scss
  src/pages/signup/style.module.scss
Labels: bug

#76 [Feat] 내가 쓴 글 path 연결
  src/pages/profile/(components)/content/index.tsx
  src/pages/profile/(components)/content/style.module.scss
  src/pages/profile/index.tsx
Labels: feat

#80 [Feat] 내가 쓴 글 이미지 처리
  src/pages/content/[contentId]/edit/index.tsx
  src/pages/profile/(components)/content/index.tsx
  src/pages/profile/(components)/content/style.module.scss
  src/pages/profile/index.tsx
Labels: feat

#82 [Bug] checkValidImgUrl 삭제 복구
  src/pages/content/[contentId]/edit/index.tsx
Labels: bug

#83 [Bug] 검색어에 띄어쓰기가 입력되는 문제
  src/components/search-bar/index.tsx
Labels: bug

#85 [Bug] 메인 페이지 로드 시, 카로셀 크기가 비좁게 출력되는 문제
  src/pages/main/component/banner-carousel/style.module.scss
Labels: bug

#87 [Bug] 회원가입 유도 화면에서 이미 가입된 유저를 위한 로그인 버튼이 없는 문제
  src/pages/need-login/index.tsx
  src/pages/need-login/style.module.scss
Labels: bug

#89 [Bug] 검색어에 이모지를 입력할 수 있는 문제
  src/components/search-bar/index.tsx
  src/constants/regex.ts
Labels: bug
